
add_newline = true

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[âŒ](bold red)"
vicmd_symbol = "[â®](bold blue)"

[time]
time_format = "%T"
format = "ğŸ•™ $time($style) "
style = "bright-white"
disabled = false

[git_status]
up_to_date = "[âœ“](bold green) "
conflicted = "âš”ï¸ "
ahead = "ğŸï¸ ğŸ’¨ Ã—${count} "
behind = "ğŸ¢ Ã—${count} "
diverged = "ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count} "
untracked = "ğŸ›¤ï¸ Ã—${count} "
stashed = "ğŸ“¦ "
modified = "ğŸ“ Ã—${count} "
staged = '[++\($count\)](green) '
renamed = "ğŸ“› Ã—${count} "
deleted = "ğŸ—‘ï¸ Ã—${count} "
style = "bright-white"
format = "$all_status$ahead_behind"
[git_commit]
tag_disabled = false
commit_hash_length = 7
tag_symbol = "ğŸ”– "
