format="$all\u001b7${fill}$time($style)\u001b8"
add_newline = true

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[âŒ](bold red)"
vicmd_symbol = "[â®](bold blue)"

[time]
time_format = "%T"
# format = "ğŸ•™ $time($style) "
style = "bold blue"
disabled = false

[fill]
symbol = " "

[git_status]
format = "$all_status$ahead_behind"

up_to_date = "[âœ“](bold green) "
conflicted = "âš”ï¸ "
ahead      = "â†‘${count}"
diverged   = "â†‘${ahead_count}â†“${behind_count}"
behind     = "â†“${count}"
stashed    = "[âš‘ $count](bold blue)"
staged     = "[âœš $count](green)"
modified   = "ğŸ“ Ã—${count} "
renamed    = "[Â»$count](green)"
deleted    = "ğŸ—‘ï¸ Ã—${count} "
style      = "bright-white"
untracked  = "[â€¦$count](cyan)"

[git_commit]
tag_disabled = false
commit_hash_length = 7
tag_symbol = "ğŸ”– "
